class Response(object) :

    PING = 'PING'
    SIGNAL_QUEUED = 'SIGNAL_QUEUED'
    ORDER_QUEUED = 'ORDER_QUEUED'
    ORDER_PLACED = 'ORDER_PLACED'
    ORDER_FILLED = 'ORDER_FILLED'
    START_TRADING = 'START_TRADING'
    FINISHED_TRADING = 'FINISHED_TRADING'
